### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by vawhitehouse** [ItaloLujanPedreschi/CamClickr#3]
- [x] You'll need an `entities.users` slice of state 
- [x] `entities.albums` won't need a url
- [x] If a photo can belong to more than one album, photos would need to keep an array of `albumIds` rather than just one `albumId`. Or you may just want an album to keep track an array of ids for all the photos that are in that album.

**Comment by ItaloLujanPedreschi** [comment]
I am creating a separate table of "links" between a photo and an album called PhotoAlbumLink. Each row will have a photoId and albumId.
